name: Reformat Markdown

on:
  # Triggers the workflow on pull requests
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  reformat:
    # Runs only if the pull request has the smartling label
    if: contains(github.event.pull_request.labels.*.name, 'smartling')
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref.sha }}
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Reformat Markdown files
        run: |
          bash .github/scripts/reformat_files_pr.sh ${{ github.repository }} ${{ github.event.pull_request.number }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Reformat Markdown files"
          branch: smartling_fixes
          delete-branch: true
          title: "Reformat Markdown files"
